### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/rpgsnack-runtime#1009]
Android: 8.0.0
Device: ZenFone 4 (ZE554KL)

```
invalid uniform location: texture "goroutine 11 [running]:\nruntime/debug.Stack(0x16f67834, 0x447d3c70, 0x13c748a0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x88\ngithub.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).run.func1(0x16f67fac)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:183 +0x3c\npanic(0x447d3c70, 0x13c748a0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1a0\ngithub.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).getUniformLocationImpl(0x44b1e584, 0x17dc2701, 0xfa, 0x446931fc, 0x7, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_mobile.go:286 +0xcc\ngithub.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*locationCache).GetUniformLocation(0x1ac40050, 0x44b1e584, 0x1, 0xfa, 0x446931fc, 0x7, 0x1631c000)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/locationcache.go:36 +0xd8\ngithub.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).uniformInt(0x44b1e584, 0x8801, 0xfa, 0x446931fc, 0x7, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_mobile.go:293 +0x54\ngithub.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*Driver).useProgram(0x44b1e538, 0x1, 0x0, 0x1, 0x0, 0x0, 0x444497dc)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/program.go:291 +0x794\ngithub.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*Driver).Draw(0x44b1e538, 0x6, 0x0, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/driver.go:106 +0x3c\ngithub.com/hajimehoshi/ebiten/internal/graphicscommand.(*drawTrianglesCommand).Exec(0x17dc2600, 0x0, 0x0, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:247 +0xac\ngithub.com/hajimehoshi/ebiten/internal/graphicscommand.(*commandQueue).Flush(0x44b1e278)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:186 +0x25c\ngithub.com/hajimehoshi/ebiten/internal/graphicscommand.(*Image).Pixels(0x17dc26a0, 0x17dc2680, 0x4, 0x4)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/image.go:113 +0xac\ngithub.com/hajimehoshi/ebiten/internal/restorable.(*Image).restore(0x1ab800c0, 0x0, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:531 +0x380\ngithub.com/hajimehoshi/ebiten/internal/restorable.(*images).restore(0x44b1d1d8, 0x0, 0x16f67e58)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:211 +0x958\ngithub.com/hajimehoshi/ebiten/internal/restorable.Restore(0x4, 0x44834fac)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:71 +0x44\ngithub.com/hajimehoshi/ebiten/internal/shareable.Restore(0x0, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:486 +0x60\ngithub.com/hajimehoshi/ebiten.(*uiContext).restoreIfNeeded(0x13c9a210, 0x44a6debc, 0x3c)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/uicontext.go:164 +0x50\ngithub.com/hajimehoshi/ebiten.(*uiContext).initializeIfNeeded(0x13c9a210, 0x2, 0x447ea070)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/uicontext.go:81 +0x28\ngithub.com/hajimehoshi/ebiten.(*uiContext).Update(0x13c9a210, 0x1abdc060, 0x2, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/uicontext.go:93 +0x2c\ngithub.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).update(0x44b1e4d0, 0x44838690, 0x13c9a210, 0x0, 0x0)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:267 +0x16c\ngithub.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).run(0x44b1e4d0, 0x1e0, 0x2fe, 0x0, 0x3fe80000, 0x0, 0x0, 0x44838690, 0x13c9a210, 0x44839050, ...)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:209 +0x168\ngithub.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop.func1(0x13c68480, 0x44b1e4d0, 0x1e0, 0x2fe, 0x0, 0x3fe80000, 0x0, 0x0, 0x44838690, 0x13c9a210, ...)\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:173 +0x94\ncreated by github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop\n\t/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:171 +0x98\n"
com.rpgsnack.runtime.mobile.Mobile.update

```

**Comment by hajimehoshi** [comment]
Sounds like an error when recovering from context lost. I don't think I can fix though...
